spring:
  application:
    name: delivery
  datasource:
    url: jdbc:mysql://localhost:3306/delivery?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: acesso_root
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: create
    show-sql: true
email:
  emailHost: imap.gmail.com
  emailPort: 993
  emailUsername: testenfe81@gmail.com
  emailPassword: acesso_total#1999
