spring:
  application:
    name: delivery
  datasource:
    url: jdbc:mysql://localhost:3306/delivery?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: acesso_root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minumum-idle: 3
      idle-timeout: 10000
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  flyway:
    url: jdbc:mysql://localhost:3306/delivery
    user: root
    password: acesso_root
    locations: classpath:db/migration,classpath:db/testdata
    #properties:
      #javax:
        #persistence:
          #schema-generation:
            #scripts:
              #action: create
              #create-target: src/main/resources/ddl.sql  GERA O DDL DO PROJETO AUTOMATICAMENTE
email:
  emailHost: imap.gmail.com
  emailPort: 993
  emailUsername: lucasbref82@gmail.com
  emailPassword: sdsi jpwb mfna plxb
server:
  port: 80

