create table city (id bigint not null auto_increment, state_id bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table data_request (duration decimal(38,2), status_code integer, id bigint not null auto_increment, request_date datetime(6) not null, responde_date datetime(6), method varchar(10) not null, uri varchar(8000) not null, headers longtext, request_body longtext, response_body longtext, primary key (id)) engine=InnoDB;
create table group_permissions (group_id bigint not null, permission_id bigint not null) engine=InnoDB;
create table group_table (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table kitchen (id bigint not null auto_increment, name varchar(30) not null, primary key (id)) engine=InnoDB;
create table payment_method (id bigint not null auto_increment, description varchar(255) not null, primary key (id)) engine=InnoDB;
create table permission (id bigint not null auto_increment, description varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table product (active bit, price decimal(38,2) not null, id bigint not null auto_increment, restaurant_id bigint, description varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table restaurant (shipping_fee decimal(10,2) not null, address_city_id bigint, change_date datetime not null, id bigint not null auto_increment, kitchen_id bigint not null, registration_date datetime not null, name varchar(30) not null, address_complement varchar(255), address_neighborhood varchar(255), address_number varchar(255), address_public_place varchar(255), address_zip_code varchar(255), primary key (id)) engine=InnoDB;
create table restaurant_payment_method (payment_method_id bigint not null, restaurant_id bigint not null) engine=InnoDB;
create table state (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table city add constraint FK6p2u50v8fg2y0js6djc6xanit foreign key (state_id) references state (id);
alter table group_permissions add constraint FK8p3uamfcq6bxmqhiofmob0a8i foreign key (permission_id) references permission (id);
alter table group_permissions add constraint FKsml6b0bncbt480boay4jc09x8 foreign key (group_id) references group_table (id);
alter table product add constraint FKp4b7e36gck7975p51raud8juk foreign key (restaurant_id) references restaurant (id);
alter table restaurant add constraint FK8pcwgn41lfg43d8u82ewn3cn foreign key (address_city_id) references city (id);
alter table restaurant add constraint FKrur1dqx79jim8s8dvdp16qc3d foreign key (kitchen_id) references kitchen (id);
alter table restaurant_payment_method add constraint FK5dxd5cjhjqf8eai6xugad3e1g foreign key (payment_method_id) references payment_method (id);
alter table restaurant_payment_method add constraint FKbjuwyavt07p2uihdqt6jtmkyj foreign key (restaurant_id) references restaurant (id);